[package]
name = "librestream"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
warp = { version = "0.4.2", features = ["server"] }
multipart = { version = "0.18.0"}
json = { version = "0.12.4" }